spring:
  application.name: erp

  datasource:
    driver-class-name: org.postgresql.Driver
    hikari.maximum-pool-size: 10
    username: central
    password: central
    port-number: 5433

server:
  port: 8085

management:
  health:
    ldap:
      enabled: false
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: ['health', 'info', 'flyway' , 'logfile']
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
    flyway:
      enabled: true
    logfile:
      enabled: true
      external-file: /var/log/${spring.application.name}/${spring.application.name}.log

logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.springframework: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.web.client: INFO
    org.springframework.context.support: INFO
    org.hibernate.engine.jdbc.env.internal.LobCreatorBuilderImpl: WARN

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    hostname: localhost
    appname: access-manager

oauth:
  endpoints:
    tokens: http://localhost:8080/auth-engine/tokens
  token: http://localhost:8080/auth-engine/oauth/token
  clientId: access-manager
  clientSecret: browser